# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                                                                       
language: python                                                                                                                                                                                         

# Versão que a aplicação suporta.                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.7.9"                                                                                                                                                                                              

os: linux
dist: xenial

jobs:
  include:
    - stage: Testes
      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;

    - script:
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
        - sonar-scanner || travis_terminate 1;
      install:
        - pip install flask flask-wtf coverage
      name: "Testes de Qualidade e Seguranca"
      addons:
        sonarcloud:
          organization: darlandelmondesschool
          token: ${SONAR_TOKEN}

    - stage: Staging Deploy
      script: skip
      name: "Deployment no Heroku"
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-darlan
        on:
          branch: main
    
    - stage: Staging Test
      name: "Testing Request HTTP via linux curl"
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - sleep 2; curl http://devopslab-darlan.herokuapp.com/ | grep -i Lab.Pipeline.DevOps || travis_terminate 1;

    - stage: Production Deploy
      script: skip
      name: "Deployment na AWS"
      deploy:
        provider: elasticbeanstalk
        access_key_id: $CHAVE_AWS
        secret_access_key: $TOKEN_AWS
        region: "sa-east-1"
        application: "DevOpsLab"
        env: "Devopslab-env"
        bucket_name: "elasticbeanstalk-sa-east-1-421462098277"
        on:
          branch: main

    - stage: Production Test
      name: "Testing Request HTTP via linux curl"
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - sleep 2; curl http://devopslab-env.eba-tczdxr6h.sa-east-1.elasticbeanstalk.com/ | grep -i Lab.Pipeline.DevOps || travis_terminate 1;

notifications:
  slack:
    secure: 2JzBAGyqDgpe5g3cy0Q19WMVnXOhZOEnhzIjpf7BEUZCBkmqsAZF+P6RtkhdkBYudM7Z2uQpRS5V8sMcY9Zfzje+3hJYFJexkpwIbv+/h9yY6Hde05CVUTMnE7GEITI5okGmfD4nf3WbPM0cKXGBymKHgVSptcSVCw56vY7fxZwLoaMCKWBAZmGjDsTbTSTrMOSXjKUlzLoaQTR0zDdTT+ma/g2noufyC0cRoT1Y5QAMa81u8LAOVdOummpKpWYiI9eY++0UlyBT/nP4VxPCvOB4kyMVFdgCGcBxktSSrjG2lAciuWHMKM7Q5ir3QdtWFwhvxTmG0SToTOB5WRilEtEGlwgbAaYh8ckGRiORIKTIxVFab1Pliq2rk7eFp0QczYQgnEWotgZExRkK8XEQ42buDKwCTkFnHzL2RT8MnAOxoqhdevZUycO8CJ+zkWgsxatCILgjzzAi/mwf1m2UDRRt5mJ496ud1VvfY1iLZj/fcjZ+krt/Z3jQhs/LQBEe5J8JlaSlSH2nPltdAbQYOaZbtYqfu4NmhFyW5N7B3rbRTI/CU8oIha7qo70TWK2Lz0n4gyyM4dz0A8Vb/1F5XmgYfotyCAPndpmeQEVHwGkCeGrwT907EyfkJQ7tT92D6GkaUPAAMNsKBC1uUt/Qd2C4k7VSosCGTsvKE1ddgJ0=